export default {
  errors: {
    // Common errors:
    unexpected_error: 'Unexpected API error',
    validation_failed: 'Validation failed',
    required: '%s is required',
    invalid_date: 'Wrong format of date',
    auth_required: 'Authorization required',
    access_denied: 'Access denied',
    invalid_value: 'Invalid value',
    bad_token: 'Bad token',
    already_exists: '%s has already registered',
    non_existent: '%s doesn\'t exist',
    invalid_username_or_password: 'Wrong username or password',
    invalid_confirm_password: 'Confirm password isn\'t the same with password',
    unknown_user: 'Unknown username',
  },

  brand: {
    name: 'Walk',
    tagline: 'Where do you go today',
  },

  titles: {
    welcome: 'Welcome',
    sign_in: 'Sign in',
    sign_up: 'Sign up',
    search: 'Search results',
    error: 'Error',
    not_found: 'Not found',
    profile: 'Your Profile',
  },

  captions: {
    start: 'Start',
    about: 'About',
    sign_in: 'Sign in',
    sign_up: 'Sign up',
    posts: 'Posts',
    upcoming: 'Upcoming',
    followers: 'Followers',
    following: 'Following',
    profile: 'Profile',
    settings: 'Settings',
    log_out: 'Log out',
    search: 'Search',
    follow: 'Follow',
    unfollow: 'Unfollow',
    add_post: 'Post',
    add_event: 'Create event',
    error: 'Error',
    success: 'Success',
    load_more: 'Load more',
    update: 'Update',
    attach_photo: 'Attach photo',
    feed: 'Recent News',
  },

  fields: {
    username: 'Username',
    password: 'Password',
    confirm_password: 'Confirm password',
    full_name: 'Full name',
    address: 'Address',
    image_url: 'Image url',
    avatar_url: 'Avatar url',
    event_date: 'Date',
    location: 'Location',
  },

  messages: {
    type_search_text: 'Start typing',
    add_post: 'Tell the world about visited place',
    no_records_found: 'No records found',
    add_event: 'Let\'s walk',
    error_title: 'Oops...',
    error_description: 'Something went wrong',
    profile: 'Profile info',
    success: 'Your data was tasty',
    joined: 'Joined on',
    signed_in: 'Signed in as',
    profile_detail: 'Change your public info',
    not_found_title: 'Not found',
    not_found_description: 'Sorry, but seems we don\'t have a such page',
    drop_images: 'Drop images here to upload',
  },
};
